### PR TITLE
[RFR] add placeholder in config

### PR DESCRIPTION
**Pull request by julestruong**

### CODE REVIEW

**Comment by julestruong** [comment]
Is this ok  now ? @djett41

**Comment by djett41** [comment]
Looks good!  I'll check out the branch, test locally, then merge it in over the weekend thanks!

**Comment by julestruong** [comment]
Thanks tell me if there is something wrong.

**Comment by djett41** [comment]
Thanks @julestruong I merged the changes in, just try to be a little more careful with the commit messages like 'oops' and 'sorry'.  I squashed your commits into a single merge commit so it's a little more readable.

Thanks again buddy!!

**Pull request closed without merging**
